name: Build DECtalk

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ubuntu:
    name: Ubuntu (latest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Ubuntu Packages
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get -y install build-essential libpulse-dev libgtk2.0-dev unzip autoconf automake

      - name: Create configure files
        working-directory: src
        run: autoreconf -i

      - name: Configure
        working-directory: src
        run: ./configure

      - name: Make DECtalk
        working-directory: src
        run: make

      - name: Create a `.tar.gz` of the dist/ folder.
        run: tar -cvzf dectalk.tar.gz -C dist/ .

      - name: Create artifacts (.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-zip
          path: dist/

      - name: Create artifacts (.tar.gz.zip)
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest-tar
          path: dectalk.tar.gz

          ubuntu:

  macosx:
    name: Mac OS X
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Mac OS X packages
        run: brew update

      - name: Install dependencies
        run: brew install autoconf automake libtool

      - name: Create configure files
        working-directory: src
        run: autoreconf -i

      - name: Configure
        working-directory: src
        run: ./configure

      - name: Make DECtalk
        working-directory: src
        run: make

      - name: Create a `.tar.gz` of the dist/ folder.
        run: tar -cvzf dectalk.tar.gz -C dist/ .

      - name: Create artifacts (.zip)
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-zip
          path: dist/

      - name: Create artifacts (.tar.gz.zip)
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-tar
          path: dectalk.tar.gz

  vs6-server2022:
    name: Visual Studio 6
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make DECtalk
        shell: cmd
        run: devops\vs6\dt_buildall.bat

      - name: Copy files to the "/dist" folder
        shell: cmd
        run: devops\vs6\dt_copyfiles.bat

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vs6
          path: dist/

  vs2022:
    name: Visual Studio 2022 (IA32 and AMD64)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Make DECtalk
        shell: cmd
        run: devops\vs2022\dt_buildall.bat

      - name: Copy files to the "/dist" folder
        shell: cmd
        run: devops\vs2022\dt_copyfiles.bat

      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vs2022
          path: dist/
